name: Run Pre-Commit Hooks

on:
  pull_request:

permissions:
  pull-requests: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: pre-commit/action@v3.0.0
